services:
  gotify:
    image: gotify/server:2.6.1
    restart: unless-stopped
    networks:
      local:
    dns: 
      - 172.30.0.3
    volumes:
      - './gotify_data:/app/data'
    labels:
      traefik.enable: "true"
      traefik.http.routers.gotify.entrypoints: "websecure" 
      traefik.http.routers.gotify.rule: "Host(`gotify.${BASE_URL_HOME}`)"
      traefik.http.routers.gotify.tls.certresolver: "myresolver"
      traefik.http.services.gotify.loadbalancer.server.port: 80 
networks:
  local:
    external: true