services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      - ACCOUNT_jd=${ACCOUNT_jd}
      - UID_jd=${UID_jd}
      - GID_jd=${GID_jd}
      - GROUPS_jd=${GROUPS_jd}
      - SAMBA_VOLUME_CONFIG_nas=${SAMBA_VOLUME_CONFIG_nas}
    ports:
      - 445:445
    cap_add:
      - CAP_NET_ADMIN
    volumes:
      - /mnt/md0/smb:/shares/location
